# Generated by Django 4.2.23 on 2025-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintType', models.CharField(blank=True, max_length=50, null=True)),
                ('Subject', models.Field(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('AssignedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateField(auto_now=True, null=True)),
                ('ResolvedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestType', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('CreatedDate', models.DateField(auto_now=True, null=True)),
                ('ResolvedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=50, null=True)),
                ('CourseCredit', models.FloatField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('Usertype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Message', models.Field(blank=True, max_length=150, null=True)),
                ('CreatedDate', models.DateField(auto_now=True, null=True)),
                ('ExpiryDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('DateofBirth', models.DateField(auto_now=True, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('JoinDate', models.DateField(auto_now=True, null=True)),
                ('ProfileImage', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('RollNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('DateofBirth', models.DateField(auto_now=True, null=True)),
                ('Semester', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('AdmissionDate', models.DateField(auto_now=True, null=True)),
                ('ProfileImage', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('Semester', models.Field(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
