# Generated by Django 4.2.23 on 2025-08-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusSenseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginPage',
            new_name='LoginTable',
        ),
    ]
