# Generated by Django 4.2.23 on 2025-08-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampusSenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='DEPARTMENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CampusSenseApp.department'),
            preserve_default=False,
        ),
    ]
