# Generated by Django 4.2.23 on 2025-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusSenseApp', '0003_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CreatedDate',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
